#!/usr/bin/env python3
import os, sys

# We define the encoding for the headers
print("Content-Type: text/html; charset=utf-8\r\n\r\n")

# We get the argument string (e.g., user=william&age=20)
query_string = os.environ.get('QUERY_STRING', '')

# Simple logic to extract the name
user_name = "Unknown_User"
if "user=" in query_string:
    # We split the string to get what is after "user="
    user_name = query_string.split("user=")[1].split("&")[0]

# Notice the double curly braces {{ }} in the CSS. 
# This prevents Python f-string errors!
print(f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CGI Response - Webserv</title>
    <style>
        body {{ 
            font-family: 'Fira Code', 'Consolas', 'Courier New', monospace; 
            margin: 0; 
            padding: 10vh 20px; 
            background-color: #1e1d1b; 
            color: #e8c37d;
            background-image: linear-gradient(rgba(232, 195, 125, 0.02) 50%, transparent 50%);
            background-size: 100% 4px;
            text-align: center;
        }}
        
        .card {{ 
            background: #262421; 
            padding: 40px; 
            border: 1px solid #4a3e2a; 
            border-radius: 6px;
            box-shadow: 0 8px 20px rgba(0,0,0,0.5);
            display: inline-block;
            max-width: 600px;
            text-align: left;
        }}
        
        h1 {{ 
            color: #f5a933;
            text-transform: uppercase;
            letter-spacing: 2px;
            text-shadow: 0 0 10px rgba(245, 169, 51, 0.3);
            margin-top: 0;
            border-bottom: 1px solid #5e4d31;
            padding-bottom: 15px;
        }}
        
        .name {{ 
            color: #1e1d1b;
            background-color: #f5a933;
            padding: 2px 8px;
            border-radius: 3px;
            margin-left: 8px;
        }}
        
        p {{
            font-size: 1.1rem;
            color: #d1b890;
            line-height: 1.6;
            margin-bottom: 20px;
        }}
        
        .btn {{ 
            display: inline-block; 
            padding: 12px 24px; 
            background: #36322d; 
            color: #e8c37d; 
            text-decoration: none; 
            border: 1px solid #5e4d31; 
            border-radius: 4px;
            font-weight: bold;
            text-transform: uppercase;
            transition: all 0.2s ease;
            margin-top: 15px;
        }}
        
        .btn:hover {{ 
            background: #f5a933; 
            color: #1e1d1b;
            border-color: #f5a933;
            box-shadow: 0 0 12px rgba(245, 169, 51, 0.4);
        }}
        
        .cursor {{
            display: inline-block;
            width: 8px;
            height: 1em;
            background-color: #f5a933;
            vertical-align: text-bottom;
            animation: blink 1s step-end infinite;
        }}

        @keyframes blink {{
            0%, 100% {{ opacity: 1; }}
            50% {{ opacity: 0; }}
        }}
    </style>
</head>
<body>
    <div class="card">
        <h1>> CGI_EXEC <span class="name">{user_name}</span></h1>
        <p>System notification: This message was dynamically generated by a Python script.</p>
        <p>Your Webserv successfully parsed the environment variables and transmitted your parameters via the CGI protocol.<span class="cursor"></span></p>
        <a href="/" class="btn">Return to Dashboard</a>
    </div>
</body>
</html>
""")